<a href="https://colab.research.google.com/github/WanatchapornS/Data-Preparation-Data-Mining/blob/main/HW03_Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**633020669-7 วนัชพร สุนิพันธ์**

ให้ทุกคนฝึกฝนด้วยตนเองก่อนคลาสในวันศุกร์
* อ่านไฟล์ใน Google Drive ของตนเองบน Google Colab
* อ่านไฟล์ในเครื่องตนเองด้วย Jupyter Notebook ในเครื่องของตน
* อ่านไฟล์ใน Google Drive ของตนเองผ่าน Jupyter Notebook ในเครื่องของตน ซึ่งสามารถสร้าง sharable link แล้วนำมาเป็น path ของไฟล์ที่ต้องการอ่านได้ (หรือปกติก็สามารถดาวน์โหลดไฟล์ลงเครื่องตนเองแล้วอ่านตามปกติ)

In [5]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/

In [8]:
import pandas as pd
data_iris = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/iris.csv')
data_iris

     sepal length  sepal width  petal length  petal width  flower type
0             5.1          3.5           1.4          0.2            0
1             4.9          3.0           1.4          0.2            0
2             4.7          3.2           1.3          0.2            0
3             4.6          3.1           1.5          0.2            0
4             5.0          3.6           1.4          0.2            0
..            ...          ...           ...          ...          ...
145           6.7          3.0           5.2          2.3            2
146           6.3          2.5           5.0          1.9            2
147           6.5          3.0           5.2          2.0            2
148           6.2          3.4           5.4          2.3            2
149           5.9          3.0           5.1          1.8            2

[150 rows x 5 columns]

In [13]:
import pandas as pd
data_diabetes = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRPggP14jHvECEu9gaM-rm94wXhKKyqz3aqOCQ7_sYq22Bp8I4sfbgRGGqrc4YHKA2oeRmOOyRQivJd/pub?output=csv')
data_diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [10]:
import os
path = '/content/drive/My Drive/Colab Notebooks/confirmed-cases.csv'
data_covid_cases = pd.read_csv(os.path.join(path))
data_covid_cases

<ipython-input-10-7a34518c9044>:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid_cases = pd.read_csv(os.path.join(path))

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,NaN,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN

In [21]:
import numpy as np

In [25]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [26]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
y = np.linspace(start = 2, stop = 10, num = 5)
y

array([ 2.,  4.,  6.,  8., 10.])

Chebyshev distance เป็นการวัดความต่างระหว่างข้อมูลแบบ $L_\infty$ norm ซึ่งเป็นกรณีพิเศษของ Minkowski distance: $\left(\sum_{i=1}^{k} \lvert x_i - y_i \rvert^r\right)^{1/r}$ ที่ $r=\infty$ โดยสามารถคำนวณค่าได้ดังนี้
$$d(x,y) = \max_{i} \left( \lvert x_{i} - y_{i} \rvert \right)$$

สร้างฟังก์ชันสำหรับคำนวณ Chebyshev distance ระหว่างเวคเตอร์ 2 เวคเตอร์ ที่แต่ละเวคเตอร์มีขนาด k มิติ (numpy array of length k)

In [33]:
def chebyshev_dis(vec1,vec2):
  max = 0
  for i in range(len(vec1)):
      max = np.max(np.abs(vec1[i] - vec2[i]))
  return max

chebyshev_dis(x, y)

6.0

Canberra distance เป็นการวัดความต่างระหว่างข้อมูลแบบ Manhattan distance ที่ถ่วงน้ำหนัก (weighted Manhattan distance) โดยคำนวณดังนี้
$$d(x,y) = \sum_{i=1}^{k} \frac{\lvert x_{i} - y_{i} \rvert}{\lvert x_{i} \rvert + \lvert y_{i} \rvert}$$

สร้างฟังก์ชันสำหรับคำนวณ Canberra distance ระหว่างเวคเตอร์ 2 เวคเตอร์ ที่แต่ละเวคเตอร์มีขนาด k มิติ

In [38]:
def canberra_dis(vec1,vec2):
  for i in range(len(vec1)):
      sum = np.sum( np.abs(vec1-vec2) / np.abs(vec1+vec2) )
  return sum

canberra_dis(x, y)

2.983116883116883

สร้างฟังก์ชันสำหรับคำนวณค่าเฉลี่ยของค่าในเวคเตอร์หนึ่ง โดยไม่ใช้ฟังก์ชันสำเร็จรูป `mean()` ใช้เพียง numpy array และการบวกลบคูณหาร

In [39]:
def f_mean(vec):
    mean = np.sum(vec) / len(vec)
    return mean
f_mean(x)

2.0

In [43]:
def f_mean(vec):
    mean = np.sum(vec) / len(vec)
    return mean
f_mean(y)

6.0

สร้างฟังก์ชันสำหรับคำนวณค่าเบี่ยงเบนมาตรฐานของค่าในเวคเตอร์หนึ่ง โดยไม่ใช้ฟังก์ชัน `std()` หรือ `stddev()` ใช้เพียง numpy array และการบวกลบคูณหาร

In [42]:
def f_std(vec):
    mean = np.mean(vec)
    diff = vec - mean
    power = diff ** 2
    var = np.mean(power)
    std = np.sqrt(var)
    return std
f_std(x)

1.4142135623730951

In [44]:
def f_std(vec):
    mean = np.mean(vec)
    diff = vec - mean
    power = diff ** 2
    var = np.mean(power)
    std = np.sqrt(var)
    return std
f_std(y)

2.8284271247461903